/// Conformed product category dimension. Shared by Dim Product, Fact Budget and Fact Target to resolve the category grain conflict.
table 'Dim Category'
	lineageTag: a61a5ac5-9363-48d9-a86e-09d25e9a715b

	/// Conformed product category shared by Sales-via-Product, Budget and Target - the single slicer that filters all three facts together.
	column Category
		dataType: string
		lineageTag: e0aed2f1-6000-4e5c-8965-cef134bac528
		sourceColumn: Category
		sortByColumn: 'Sort Order'

	column 'Sort Order'
		dataType: int64
		isHidden
		lineageTag: 1371e01a-7768-450e-bb12-149f21e7f127
		sourceColumn: Sort Order

	partition 'Dim Category' = m
		mode: import
		source =
				let
				    Source = Csv.Document(File.Contents(pSeedDataFolder & "\Dim_Product.csv"), [Delimiter=",", Encoding=65001, QuoteStyle=QuoteStyle.Csv]),
				    Promoted = Table.PromoteHeaders(Source, [PromoteAllScalars=true]),
				    Categories = Table.Distinct(Table.SelectColumns(Promoted, {"Category"})),
				    Mapped = Table.AddColumn(Categories, "Sort Order", each if [Category] = "Technology" then 1 else if [Category] = "Furniture" then 2 else 3, Int64.Type),
				    Sorted = Table.Sort(Mapped, {{"Sort Order", Order.Ascending}})
				in
				    Sorted

