/// Conformed date dimension, 2024-01-01 to 2026-12-31 at daily grain.
table 'Dim Date'
	lineageTag: cc9d7fcc-1807-47d6-b352-88fd57da5f65
	dataCategory: Time

	column 'Date Key'
		dataType: int64
		isHidden
		lineageTag: 756c590f-5306-4eee-bc56-6f55c2ee17f0
		summarizeBy: none
		sourceColumn: Date Key

		annotation SummarizationSetBy = User

	/// Calendar date, one row per day (2024-01-01 to 2026-12-31). Primary date column for time intelligence; table is marked as a date table.
	column Date
		dataType: dateTime
		isUnique
		formatString: dd-mmm-yyyy
		lineageTag: dd6c3631-a799-45f6-86e8-04e1eac57de5
		sourceColumn: Date

	/// Calendar year of the date. Numeric so it sorts correctly; use for year grouping and YoY context.
	column Year
		dataType: int64
		lineageTag: 91f2366a-51b1-4118-a69e-feaf557f2b6f
		summarizeBy: none
		sourceColumn: Year

		annotation SummarizationSetBy = User

	/// Calendar quarter label derived from the date; for quarterly grouping and QTD analysis.
	column Quarter
		dataType: string
		lineageTag: d8dd89d3-d60b-4acb-9762-5904f6195d4e
		sourceColumn: Quarter

	/// Calendar month number 1-12. Sort key for Month Name and Year Month; never aggregate.
	column 'Month Number'
		dataType: int64
		lineageTag: 2af704b9-0e02-47a9-b574-9f1f36f105e4
		summarizeBy: none
		sourceColumn: Month Number

	/// Month name (Jan-Dec) for axis labels; sorted by Month Number so it orders chronologically, not alphabetically.
	column 'Month Name'
		dataType: string
		lineageTag: ae574ce9-95e8-44ad-8ecb-d3bd58dc3f2b
		sourceColumn: Month Name
		sortByColumn: 'Month Number'

	/// Day of week name derived from the date; use for weekly pattern analysis.
	column 'Day of Week'
		dataType: string
		lineageTag: d9dd6eb8-dedb-410e-8d96-7c26c029c965
		sourceColumn: Day of Week

	/// 1 = working day, 0 = non-working day per the calendar; use to compare working vs non-working performance.
	column 'Is Working Day'
		dataType: int64
		lineageTag: e7021a06-87e2-482c-9d9f-7fe76b98ecfc
		summarizeBy: none
		sourceColumn: Is Working Day

		annotation SummarizationSetBy = User

	/// Sort key for Year Month (YYYYMM). Hidden technical column.
	column 'Year Month Sort' = 'Dim Date'[Year] * 100 + 'Dim Date'[Month Number]
		dataType: int64
		isHidden
		lineageTag: 76e9b174-6dba-44ff-9eaa-457030e5fe45

	/// Month label for monthly trend axes, e.g. Jan 2024.
	column 'Year Month' = FORMAT('Dim Date'[Date], "MMM YYYY")
		dataType: string
		lineageTag: d0fe4072-59ad-4ac0-b1a5-24206b585aed
		sortByColumn: 'Year Month Sort'

	/// Calendar drill path for time analysis.
	hierarchy Calendar
		lineageTag: d0d22823-a5dc-490c-a64f-10af4b39a029

		level Year
			lineageTag: 4df1f86b-1d8f-4692-85f7-9f781381bdfd
			column: Year

		level Quarter
			lineageTag: f6c38c85-115c-4821-b4d2-43ae1fe68362
			column: Quarter

		level Month
			lineageTag: 8fa25c29-6a24-42f6-b3bc-0e3621c28c06
			column: 'Month Name'

		level Day
			lineageTag: 77b9872a-0420-4156-b3b0-e7c836f41b26
			column: Date

	partition 'Dim Date' = m
		mode: import
		source =
				let
				    Source = Csv.Document(File.Contents(pSeedDataFolder & "\Dim_Date.csv"), [Delimiter=",", Encoding=65001, QuoteStyle=QuoteStyle.Csv]),
				    Promoted = Table.PromoteHeaders(Source, [PromoteAllScalars=true]),
				    Renamed = Table.RenameColumns(Promoted, {{"DateKey", "Date Key"}, {"Month", "Month Number"}, {"MonthName", "Month Name"}, {"DayOfWeek", "Day of Week"}, {"IsWorkingDay", "Is Working Day"}}),
				    Typed = Table.TransformColumnTypes(Renamed, {{"Date Key", Int64.Type}, {"Date", type datetime}, {"Year", Int64.Type}, {"Quarter", type text}, {"Month Number", Int64.Type}, {"Month Name", type text}, {"Day of Week", type text}, {"Is Working Day", Int64.Type}})
				in
				    Typed

	annotation PBI_ResultType = Table

