/// P&L reporting structure with sort order and sign modifier for account-level rolling.
table 'Dim Financial Accounts'
	lineageTag: 791413e3-ee28-4448-9454-228c34db479f

	column 'Account Key'
		dataType: int64
		isHidden
		lineageTag: 42cdf29d-388f-446b-8284-46975d840178
		sourceColumn: Account Key

	/// GL account line in the P&L layout. Use with [P&L Amount]; Sort Order drives statement order and Sign Modifier flips cost/opex lines negative.
	column Account
		dataType: string
		lineageTag: a4b1ef83-33f4-4bf8-92be-b8972be469bb
		sourceColumn: Account
		sortByColumn: 'Sort Order'

	/// Top-level P&L grouping of the account (e.g. Revenue). [Net Revenue] filters Header = Revenue; use it to section the statement.
	column Header
		dataType: string
		lineageTag: 8b87f3ef-064a-4054-9ea5-c6aed06573c0
		sourceColumn: Header

	/// Technical sort order for the P&L account layout. Hidden so the P&L renders in statement order without exposing the key.
	column 'Sort Order'
		dataType: int64
		isHidden
		lineageTag: e34abb8d-1e5b-48e0-96b5-12e9eb5e33bc
		sourceColumn: Sort Order

	/// Multiplier (+1/-1) applied by [P&L Amount] so revenue reads positive and cost/opex lines flip negative. Never aggregate or display directly.
	column 'Sign Modifier'
		dataType: int64
		lineageTag: ed16a2d4-9a5b-455e-a271-d1ff40ba96da
		summarizeBy: none
		sourceColumn: Sign Modifier

	partition 'Dim Financial Accounts' = m
		mode: import
		source =
				let
				    Source = Csv.Document(File.Contents(pSeedDataFolder & "\Dim_Financial_Accounts.csv"), [Delimiter=",", Encoding=65001, QuoteStyle=QuoteStyle.Csv]),
				    Promoted = Table.PromoteHeaders(Source, [PromoteAllScalars=true]),
				    Renamed = Table.RenameColumns(Promoted, {{"AccountKey", "Account Key"}, {"AccountName", "Account"}, {"SortOrder", "Sort Order"}, {"SignModifier", "Sign Modifier"}}),
				    Typed = Table.TransformColumnTypes(Renamed, {{"Account Key", Int64.Type}, {"Account", type text}, {"Header", type text}, {"Sort Order", Int64.Type}, {"Sign Modifier", Int64.Type}})
				in
				    Typed

	annotation PBI_ResultType = Table

