/// Forecast scenario dimension with business sort order (Conservative, Base, Optimistic).
table 'Dim Scenario'
	lineageTag: be86fd7d-e2e1-468a-82f5-39c62c560aa5

	/// Forecast scenario label (Base, Optimistic, Conservative) in business sort order. Slice here to isolate one scenario across forecast measures.
	column Scenario
		dataType: string
		lineageTag: 0924ff54-2704-48d0-8258-8490cab8a2c6
		sourceColumn: Scenario
		sortByColumn: 'Sort Order'

	column 'Sort Order'
		dataType: int64
		isHidden
		lineageTag: cb452e81-e4a8-4d2c-9de2-857e2c2b77ae
		sourceColumn: Sort Order

	partition 'Dim Scenario' = m
		mode: import
		source =
				let
				    Source = Csv.Document(File.Contents(pSeedDataFolder & "\Fact_Target.csv"), [Delimiter=",", Encoding=65001, QuoteStyle=QuoteStyle.Csv]),
				    Promoted = Table.PromoteHeaders(Source, [PromoteAllScalars=true]),
				    Scenarios = Table.Distinct(Table.SelectColumns(Promoted, {"Scenario"})),
				    Mapped = Table.AddColumn(Scenarios, "Sort Order", each if [Scenario] = "Conservative" then 1 else if [Scenario] = "Base" then 2 else 3, Int64.Type),
				    Sorted = Table.Sort(Mapped, {{"Sort Order", Order.Ascending}})
				in
				    Sorted

