/// Forecast fact at month x Category x Scenario grain (Base, Optimistic, Conservative).
table 'Fact Target'
	lineageTag: 7ef5ad6c-5aeb-4e44-97a0-8043bfbd75a6

	column 'Date Key'
		dataType: int64
		isHidden
		lineageTag: a87183e4-a8c1-433c-ac6c-5256464ae23f
		sourceColumn: Date Key

	/// Category the forecast line applies to (grain: month x category x scenario). Filter via Dim Category[Category] for consistent cross-fact slicing.
	column Category
		dataType: string
		isHidden
		lineageTag: 69828aee-dc7b-4573-9bbe-62a015b537da
		sourceColumn: Category

	/// Scenario of the forecast line (Base/Optimistic/Conservative). Prefer slicing via Dim Scenario[Scenario]; [Target Sales] always uses Base regardless.
	column Scenario
		dataType: string
		isHidden
		lineageTag: 30c17fe4-53ef-4353-9412-d948603c16b7
		sourceColumn: Scenario

	/// Forecast sales value at month x category x scenario grain. Additive; base for [Target Sales] (Base scenario) and scenario measures.
	column 'Forecast Amount'
		dataType: decimal
		lineageTag: 081a019e-ebf7-4bc6-8520-616b13e64af2
		sourceColumn: Forecast Amount

	partition 'Fact Target' = m
		mode: import
		source =
				let
				    Source = Csv.Document(File.Contents(pSeedDataFolder & "\Fact_Target.csv"), [Delimiter=",", Encoding=65001, QuoteStyle=QuoteStyle.Csv]),
				    Promoted = Table.PromoteHeaders(Source, [PromoteAllScalars=true]),
				    Renamed = Table.RenameColumns(Promoted, {{"DateKey", "Date Key"}, {"ForecastAmount", "Forecast Amount"}}),
				    Typed = Table.TransformColumnTypes(Renamed, {{"Date Key", Int64.Type}, {"Category", type text}, {"Scenario", type text}, {"Forecast Amount", type number}})
				in
				    Typed

	annotation PBI_ResultType = Table

